/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <pthread.h>
#include "rtsp_demo.h"

#define LOG_TAG "RTSP_DEMO"
static pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
static rtsp_demo_handle demo = NULL;
static rtsp_session_handle session = NULL;

/* Header for class com_example_LiveCamera_rtsp_demo_jni */

/*
 * Class:     com_example_LiveCamera_rtsp_demo_jni
 * Method:    start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_LiveCamera_rtsp_1demo_1jni_start
  (JNIEnv *env, jobject obj, jint port, jstring path, jlong pts)
{
    const char *szpath = NULL;
    pthread_mutex_init(&mutex, NULL);

    demo = rtsp_new_demo(port);
    if (!demo) {
        __android_log_print(ANDROID_LOG_INFO, LOG_TAG, "rtsp_new_demo failed");
        return -1;
    }

    szpath = (*env)->GetStringUTFChars(env, path, 0);
    session = rtsp_new_session(demo, szpath);
    if (!session) {
        __android_log_print(ANDROID_LOG_INFO, LOG_TAG, "rtsp_new_session failed");
        rtsp_del_demo(demo);
        demo = NULL;
        return -1;
    }

    rtsp_set_video(session, RTSP_CODEC_ID_VIDEO_H264, NULL, 0);
    rtsp_set_audio(session, RTSP_CODEC_ID_AUDIO_AAC, NULL, 0);

    rtsp_sync_video_ts(session, pts, rtsp_get_ntptime());
    rtsp_sync_audio_ts(session, pts, rtsp_get_ntptime());

    rtsp_do_event(demo);

    __android_log_print(ANDROID_LOG_INFO, LOG_TAG, 
            "rtsp demo starting ... rtsp://127.0.0.1:%d%s", port, szpath);
    return 0;
}

/*
 * Class:     com_example_LiveCamera_rtsp_demo_jni
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_LiveCamera_rtsp_1demo_1jni_stop
  (JNIEnv *env, jobject obj)
{
    if (session) {
        rtsp_del_session(session);
        session = NULL;
    }
    if (demo) {
        rtsp_del_demo(demo);
        demo = NULL;
    }
    pthread_mutex_destroy(&mutex);

    __android_log_print(ANDROID_LOG_INFO, LOG_TAG, "rtsp demo stop ...");
}

/*
 * Class:     com_example_LiveCamera_rtsp_demo_jni
 * Method:    h264_send
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_example_LiveCamera_rtsp_1demo_1jni_h264_1send
  (JNIEnv *env, jobject obj, jbyteArray buffer, jint length, jlong pts)
{
    int ret;
    unsigned char *frame;
    if (!session) {
        __android_log_print(ANDROID_LOG_INFO, LOG_TAG, "no rtsp demo");
        return -1;
    }

    pthread_mutex_lock(&mutex);

    frame = (unsigned char*)(*env)->GetByteArrayElements(env, buffer, NULL);

    ret = rtsp_tx_video(session, frame, length, pts);
    if (ret < 0) {
        __android_log_print(ANDROID_LOG_INFO, LOG_TAG, "rtsp_tx_video failed");
    }

    do {
        ret = rtsp_do_event(demo);
        if (ret < 0) {
            __android_log_print(ANDROID_LOG_INFO, LOG_TAG, "rtsp_do_event failed");
        }
    } while (ret > 0);

    (*env)->ReleaseByteArrayElements(env, buffer, (jbyte*)frame, 0);

    pthread_mutex_unlock(&mutex);
    return ret;
}

static const unsigned char *find_aac_adts (const unsigned char *buff, int len, int *size)
{
	const unsigned char *s = buff;
	while (len > 2) {
		if (s[0] == 0xff && (s[1] & 0xf0) == 0xf0) {
			break;
		}
		buff ++;
		len --;
	}

	if (len <= 2)
		return NULL;

	//aac_frame_length
	*size = 0;
	*size |= (s[3] & 3) << 11;
	*size |= (s[4] << 3);
	*size |= (s[5] >> 5);

	if (*size > len)
		return NULL;

	return s;
}
/*
 * Class:     com_example_LiveCamera_rtsp_demo_jni
 * Method:    aac_send
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_example_LiveCamera_rtsp_1demo_1jni_aac_1send
  (JNIEnv *env, jobject obj, jbyteArray buffer, jint length, jlong pts)
{
    int ret;
    const unsigned char *buff;
    if (!session) {
        __android_log_print(ANDROID_LOG_INFO, LOG_TAG, "no rtsp demo");
        return -1;
    }

    pthread_mutex_lock(&mutex);

    buff = (unsigned char*)(*env)->GetByteArrayElements(env, buffer, NULL);

    do {
        const unsigned char *frame;
        int size;

        frame = find_aac_adts(buff, length, &size);
        if (!frame) {
            ret = rtsp_tx_audio(session, buff, length, pts);
            if (ret < 0) {
                __android_log_print(ANDROID_LOG_INFO, LOG_TAG, "rtsp_tx_audio failed");
            }
            break;
        }

        ret = rtsp_tx_audio(session, frame, size, pts);
        if (ret < 0) {
            __android_log_print(ANDROID_LOG_INFO, LOG_TAG, "rtsp_tx_audio failed");
        }

        length = length - (frame - buff + size);
        buff = frame + size;
    } while (length > 0);

    do {
        ret = rtsp_do_event(demo);
        if (ret < 0) {
            __android_log_print(ANDROID_LOG_INFO, LOG_TAG, "rtsp_do_event failed");
        }
    } while (ret > 0);

    (*env)->ReleaseByteArrayElements(env, buffer, (jbyte*)buff, 0);

    pthread_mutex_unlock(&mutex);
    return ret;
}

