/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_LiveCamera_rtsp_demo_jni */

#ifndef _Included_com_example_LiveCamera_rtsp_demo_jni
#define _Included_com_example_LiveCamera_rtsp_demo_jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_LiveCamera_rtsp_demo_jni
 * Method:    start
 * Signature: (ILjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_example_LiveCamera_rtsp_1demo_1jni_start
  (JNIEnv *, jobject, jint, jstring, jlong);

/*
 * Class:     com_example_LiveCamera_rtsp_demo_jni
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_LiveCamera_rtsp_1demo_1jni_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_example_LiveCamera_rtsp_demo_jni
 * Method:    h264_send
 * Signature: ([BIJ)I
 */
JNIEXPORT jint JNICALL Java_com_example_LiveCamera_rtsp_1demo_1jni_h264_1send
  (JNIEnv *, jobject, jbyteArray, jint, jlong);

/*
 * Class:     com_example_LiveCamera_rtsp_demo_jni
 * Method:    aac_send
 * Signature: ([BIJ)I
 */
JNIEXPORT jint JNICALL Java_com_example_LiveCamera_rtsp_1demo_1jni_aac_1send
  (JNIEnv *, jobject, jbyteArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
